version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/projectmanager
      - SECRET_KEY=temporarysecretkey
      - ENVIRONMENT=development
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=projectmanager
    networks:
      - app-network
    restart: always

volumes:
  postgres_data:
  backend_data:

networks:
  app-network:
